test reports

diff --git a/.github/actions/test/action.yml b/.github/actions/test/action.yml
--- a/.github/actions/test/action.yml
+++ b/.github/actions/test/action.yml
@@ -17,11 +17,23 @@ runs:
   using: "composite"
   steps:
     - name: Test
-      run: python3 allTests.py --workers=3 --language=${{ inputs.language }} ${{ inputs.flags }}
+      run: python3 allTests.py --workers=3 test-report.xml --language=${{ inputs.language }} ${{ inputs.flags }}
       shell: bash
       if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
 
     - name: Test
-      run: python allTests.py --platform=x64 --workers=3 --language=${{ inputs.language }} ${{ inputs.flags }}
+      run: python allTests.py --export-xml test-report.xml --platform=x64 --workers=3 --language=${{ inputs.language }} ${{ inputs.flags }}
       shell: powershell
       if: startsWith(matrix.os, 'windows')
+
+    # - name: Publish Test Report
+    #     uses: mikepenz/action-junit-report@v4
+    #     if: success() || failure() # always run even if the previous step fails
+    #     with:
+    #       report_paths: 'test-report.xml'
+
+    - name: Test Summary
+      uses: test-summary/action@v2
+      with:
+        paths: "test-report.xml"
+      if: always()
