Fixes for nightly IceGrid GUI DMG workflow

diff --git a/.github/workflows/build-brew-packages.yml b/.github/workflows/build-brew-packages.yml
--- a/.github/workflows/build-brew-packages.yml
+++ b/.github/workflows/build-brew-packages.yml
@@ -12,6 +12,10 @@ on:
       quality:
         required: true
         type: string
+      run_id:
+        description: "The run ID to use for downloading the IceGrid GUI dmg artifact"
+        required: true
+        type: string
   workflow_dispatch:
     inputs:
       ice_version:
@@ -24,6 +28,9 @@ on:
         description: "Release quality (e.g., stable, nightly, RC)"
         required: true
         default: "nightly"
+      run_id:
+        description: "The run ID to use for downloading the IceGrid GUI dmg artifact"
+        required: true
 
 permissions:
   contents: write
@@ -45,8 +52,16 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          gh run download --repo ${{ github.repository }} --name icegridgui-macos-app --dir staging
-          icegridgui_dmg_sha256=$(shasum -a 256 "staging/IceGridGUI.dmg" | cut -d ' ' -f 1)
+          set -o pipefail
+
+          gh run download "${{ inputs.run_id }}" --repo ${{ github.repository }} --name icegridgui-macos-app --dir staging
+          icegridgui_dmg_sha256=$(shasum -a 256 "staging/IceGridGUI-${{ inputs.ice_version }}.dmg" | cut -d ' ' -f 1)
+
+          if [[ -z "$icegridgui_dmg_sha256" ]]; then
+            echo "Failed to calculate SHA256 checksum for IceGrid GUI DMG"
+            exit 1
+          fi
+
           echo "icegridgui_dmg_sha256=$icegridgui_dmg_sha256" >> $GITHUB_OUTPUT
 
       - name: Update Nightly Tap
